name: 'Debtmap - Code Complexity Analyzer'
description: 'Analyze code complexity and identify high-risk areas by correlating complexity metrics with test coverage'
author: 'iepathos'
branding:
  icon: 'activity'
  color: 'orange'

inputs:
  lcov-file:
    description: 'Path to LCOV coverage file (optional - enables risk correlation analysis)'
    required: false
    default: ''

  path:
    description: 'Path to the project to analyze'
    required: false
    default: '.'

  debtmap-version:
    description: 'Version of debtmap to use (latest or specific version like v0.1.0)'
    required: false
    default: 'latest'

outputs:
  report-path:
    description: 'Path to the generated report file'
    value: ${{ steps.analyze.outputs.report-path }}

runs:
  using: 'composite'
  steps:
    - name: Install debtmap
      shell: bash
      run: |
        # Detect platform
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)

        # Map to release binary names
        case "${OS}-${ARCH}" in
          linux-x86_64)    PLATFORM="x86_64-unknown-linux-gnu" ;;
          linux-aarch64)   PLATFORM="aarch64-unknown-linux-gnu" ;;
          darwin-x86_64)   PLATFORM="x86_64-apple-darwin" ;;
          darwin-arm64)    PLATFORM="aarch64-apple-darwin" ;;
          *)
            echo "Unsupported platform: ${OS}-${ARCH}"
            exit 1
            ;;
        esac

        # Get version
        VERSION="${{ inputs.debtmap-version }}"
        if [ "$VERSION" == "latest" ]; then
          VERSION=$(curl -sSL https://api.github.com/repos/iepathos/debtmap/releases/latest | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
        fi
        [[ "$VERSION" != v* ]] && VERSION="v$VERSION"

        # Download and install
        URL="https://github.com/iepathos/debtmap/releases/download/${VERSION}/debtmap-${PLATFORM}"
        echo "Installing debtmap ${VERSION} for ${PLATFORM}..."
        curl -sSL -o debtmap "$URL"
        chmod +x debtmap
        ./debtmap --version

    - name: Run debtmap analysis
      id: analyze
      shell: bash
      run: |
        # Build the debtmap command
        CMD="./debtmap analyze ${{ inputs.path }}"

        # Add lcov file if provided
        if [ -n "${{ inputs.lcov-file }}" ]; then
          CMD="$CMD --lcov ${{ inputs.lcov-file }}"
        fi

        # Output to markdown format
        OUTPUT_FILE="debtmap-report.md"
        CMD="$CMD --format markdown --output $OUTPUT_FILE"

        # Run the analysis
        echo "Running: $CMD"
        $CMD

        # Set output
        echo "report-path=$OUTPUT_FILE" >> $GITHUB_OUTPUT

        # Generate GitHub step summary
        if [ -n "$GITHUB_STEP_SUMMARY" ]; then
          {
            echo "## 📊 Debtmap Analysis Results"
            echo ""
            if [ -f "$OUTPUT_FILE" ]; then
              cat "$OUTPUT_FILE"
            else
              echo "Analysis complete. Report saved to: $OUTPUT_FILE"
            fi
          } >> "$GITHUB_STEP_SUMMARY"
        fi

    - name: Upload debtmap report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: debtmap-report
        path: debtmap-report.md
        retention-days: 7